sudo: required
services:
  - docker

before_install:
  - docker build -t naveen735363/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true naveen735363/react-test npm test

after-success:
  - docker build -t naveen735363/multi-client ./client
  - docker build -t naveen735363/multi-nginx ./nginx
  - docker build -t naveen735363/multi-server ./server
  - docker build -t naveen735363/multi-worker ./worker

  - docker login -u $DOCKER_ID -p $DOCKER_PASSWORD docker.io
  - docker push naveen735363/multi-client
  - docker push naveen735363/multi-nginx
  - docker push naveen735363/multi-server
  - docker push naveen735363/multi-worker
